framework = "MapKit"
crate = "objc2-map-kit"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
macos = "10.9"
maccatalyst = "13.0"
ios = "3.0"
tvos = "9.2"
watchos = "2.0"
visionos = "1.0"

external.CNPostalAddress.module = "Contacts.CNPostalAddress"

# Needs proper support for iOS
class.MKMapItemRequest.methods."initWithMapFeatureAnnotation:".skipped = true
class.MKMapItemRequest.methods.mapFeatureAnnotation.skipped = true
class.MKMapItemRequest.methods.featureAnnotation.skipped = true

##
## Safety
##

# Breaks type-safety, you must check encodings before accessing a value.
class.NSValue.unsafe = true
