[package]
name = "test-assembly"
version = "0.1.0"
edition.workspace = true
publish = false
repository.workspace = true
license.workspace = true

build = "build.rs"

[lints]
workspace = true

[dependencies]
cargo_metadata = "0.22.0"
rustc-demangle = "0.1"
regex = "1.6"
lazy_static = "1.4.0"

[package.metadata.release]
release = false
