framework = "SceneKit"
crate = "objc2-scene-kit"
required-crates = ["objc2", "objc2-foundation"]
undesired-default-dependencies = ["objc2-open-gl", "objc2-gl-kit"] # OpenGL is deprecated
custom-lib-rs = true
macos = "10.8"
maccatalyst = "13.1"
ios = "8.0"
tvos = "9.0"
watchos = "3.0"
visionos = "1.0"

external.AVAudioEngine.module = "AVFAudio.AVAudioEngine"
external.AVAudioEnvironmentNode.module = "AVFAudio.AVAudioEnvironmentNode"
external.AVAudioNode.module = "AVFAudio.AVAudioNode"
external.JSContext.module = "JavaScriptCore.JSContext"

# Both protocol and class
protocol.SCNAnimation.renamed = "SCNAnimationProtocol"

# Needs SpriteKit (potential recursion, unsure which framework should depend on which)
protocol.SCNSceneRenderer.methods."presentScene:withTransition:incomingPointOfView:completionHandler:".skipped = true
protocol.SCNSceneRenderer.methods."overlaySKScene".skipped = true
protocol.SCNSceneRenderer.methods."setOverlaySKScene:".skipped = true

##
## Safety
##

# Breaks type-safety, you must check encodings before accessing a value.
class.NSValue.unsafe = true
