framework = "XCUIAutomation"
crate = "objc2-xc-ui-automation"
required-crates = ["objc2", "objc2-foundation", "bitflags"]
link = false # Introduced later than XCTest, so linking directly to this is inadvisable
located-outside-sdk = true
custom-lib-rs = true
# Xcode 16.3, though available inside XCTest for longer.
macos = "10.9"
maccatalyst = "13.0"
ios = "7.0"
tvos = "9.0"
watchos = "2.0"
visionos = "1.0" # TODO: Documented as not available here, but this seems to be untrue?

class.XCUIElementQuery.main-thread-only = true

##
## Safety
##

# SAFETY: XCUIAutomation is well-behaved, and since it's only used for test
# code, it doesn't matter _that_ much anyhow if it's unsound (though we'd
# still like to avoid it of course).
unsafe-default-safety.property-getters = true
unsafe-default-safety.property-setters = true
unsafe-default-safety.instance-methods = true
unsafe-default-safety.class-methods = true
unsafe-default-safety.functions = true
unsafe-default-safety.not-bounds-affecting = false
