framework = "UniformTypeIdentifiers"
crate = "objc2-uniform-type-identifiers"
required-crates = ["objc2", "objc2-foundation"]
macos = "11.0"
maccatalyst = "14.0"
ios = "14.0"
tvos = "14.0"
watchos = "7.0"
visionos = "1.0"

##
## Safety
##

# SAFETY: UniformTypeIdentifiers is well-behaved.
unsafe-default-safety.property-getters = true
unsafe-default-safety.property-setters = true
unsafe-default-safety.instance-methods = true
unsafe-default-safety.class-methods = true
unsafe-default-safety.functions = true
unsafe-default-safety.not-bounds-affecting = false
