framework = "CoreVideo"
crate = "objc2-core-video"
required-crates = ["objc2-core-foundation"]
undesired-default-dependencies = ["objc2-open-gl"] # OpenGL is deprecated
custom-lib-rs = true
macos = "10.4"
maccatalyst = "13.0"
ios = "4.0"
tvos = "9.0"
watchos = "4.0"
visionos = "1.0"

external.__IOSurface.module = "IOSurface.IOSurfaceRef"

# `cf_consumed`, requires manual handling
fn.CVOpenGLBufferRelease.skipped = true
fn.CVDisplayLinkRelease.skipped = true
fn.CVOpenGLBufferPoolRelease.skipped = true
fn.CVOpenGLTextureRelease.skipped = true
fn.CVPixelBufferPoolRelease.skipped = true
fn.CVPixelBufferRelease.skipped = true
fn.CVOpenGLTextureCacheRelease.skipped = true
fn.CVBufferRelease.skipped = true

# Unknown how to handle the calling convention here?
fn.CVMetalTextureGetCleanTexCoords.skipped = true
fn.CVOpenGLTextureGetCleanTexCoords.skipped = true
fn.CVOpenGLESTextureGetCleanTexCoords.skipped = true

fn.CVMetalBufferGetTypeID.unsafe = false
fn.CVMetalTextureGetTypeID.unsafe = false
fn.CVOpenGLBufferGetTypeID.unsafe = false
fn.CVOpenGLTextureGetTypeID.unsafe = false
fn.CVPixelBufferGetTypeID.unsafe = false

# Naming conflicts with the newer Copy variants.
fn.CVBufferGetAttachment.renamed = "get_attachment"
fn.CVBufferGetAttachments.renamed = "get_attachments"

# TODO(breaking): Make these nonnull
static.kCVImageBufferPostDecodeProcessingSequenceMetadataKey.nullability = "nullable"
static.kCVImageBufferPostDecodeProcessingFrameMetadataKey.nullability = "nullable"
