[features]
# TODO(breaking): Remove this
GKGridGraph = [
    "objc2-foundation/NSArray",
    "objc2-foundation/NSObject",
    "GKGraphNode",
]
GKMeshGraph = [
    "bitflags",
    "objc2-foundation/NSArray",
    "objc2-foundation/NSObject",
    "GKGraphNode",
]
GKObstacleGraph = [
    "objc2-foundation/NSArray",
    "objc2-foundation/NSObject",
    "GKGraphNode",
]
